### Array in Numpy

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(np.__version__)

[1 2 3 4 5]
2.3.2


### 2D array in numpy

In [12]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3D array

In [23]:
import numpy as np
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [28]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


### Create an array with 5 dims

In [34]:
import numpy as np
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print('Number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions: 5


### Access the element on the first row and second column

In [37]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('2nd element on 1st row:', arr[0,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row: 2


### Iterate through 3D array

In [39]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
for i in np.nditer(arr):
    print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8


### Join two numpy arrays

In [42]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


### Searching a numpy array

In [52]:
import numpy as np
arr = np.array([4,1,2,3,4,5,4,4,6,7,8,9,10,4])
x = np.where(arr==4)
print(x)

(array([ 0,  4,  6,  7, 13]),)


### Sorting numpy arrays

In [53]:
import numpy as np
arr = np.array([23,12,56,122,768])
print(np.sort(arr))

[ 12  23  56 122 768]


In [55]:
import numpy as np
arr = np.array([12,67,187,126,76,1676])
x = [True,False,True,False,True,True]
newarr = arr[x]
print(newarr)

[  12  187   76 1676]


### Finding Mean

In [ ]:
import numpy as np
speed = np.array